### ISSUE TITLE
Nuisance: auto-widen the columns after importing

### ISSUE THREAD

**Issue by Tzunoch** [aaOpenSource/Galaxy-CSV-Processor#4]
This is just a nuisance issue.  I will take a look at it in a couple weeks if no one else does.

**Comment by arobinsongit** [comment]
That should be easy enough.

**Comment by arobinsongit** [comment]
Issue closed by commit 235a413302435c94d17bf737f9528ac02f9613da

**Comment by arobinsongit** [comment]
Issue closed by commit 235a413302435c94d17bf737f9528ac02f9613da
